AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  TaskName:
    Description: Task familly  name
    Type: String
  NodeCount:
    Description: Nummbber of nodes to be deployed to (= host nodes in cluster)
    Type: Number
    Default: 2
  Cluster:
    Description: Cluster ARN
    Type: String
    Default: "components-services-prod-ecs-backoffices-cluster-ECSBackofficesCluster-1BI0LPGQ6OOL6-ECSCluster-GZ6SYJH09YVA"
  DockerImageName:
    Description: Docker image name on Quay repository
    Type: String
  TaskMemory:
    Description: Allocated memory for task
    Type: Number
    Default: '512'
  LogGroupName:
    Type: String
    Default: awslogs-docker
  LogRegion:
    Type: String
    Default: us-west-1
Resources:

  Service:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref Cluster
      DesiredCount: !Ref NodeCount
      PlacementConstraints: 
        Type: distinctInstance
      ServiceName: !Ref TaskName
      TaskDefinition: !Ref TaskDefinition
      
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
      - Name: !Ref TaskName
        Image: !Ref DockerImageName
        PortMappings:
        - ContainerPort: 9999
          HostPort: 9999
          Protocol: tcp
        - ContainerPort: 9997
          HostPort: 9997
          Protocol: tcp
        - ContainerPort: 41414
          HostPort: 41414
          Protocol: tcp
        LogConfiguration:
          LogDriver: awslogs
          Options:
            awslogs-group: !Ref LogGroupName
            awslogs-region: !Ref LogRegion
            awslogs-stream-prefix: !Ref TaskName
        Memory: !Ref TaskMemory
        Essential: true
        Command: ["agent", "-n", "agent", "-c", "/etc/flume-ng/conf", "-f", "/etc/flume-ng/conf/flume.conf"]
      Family: !Ref TaskName
